env:
  browser: true
  commonjs: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  sourceType: module
  ecmaVersion: latest
rules:
  no-unused-vars: off
  no-undef: off
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
